alphavantage_api = "YOUR_ALPHAVANTAGE_API_KEY"
STOCK = "" 
LIMIT = ""
TOKEN = "YOUR_DISCORD_BOT_TOKEN"
GUILD_ID = int("YOUR_DISCORD_GUILD_ID")
CHANNEL_ID = int("YOUR_DISCORD_CHANNEL_ID")
alphavantage_api = "YOUR_ALPHAVANTAGE_API_KEY"
